### Урок 6. Домашняя работа

In [1]:
import numpy as np
from math import sqrt

1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [2]:
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

In [3]:
zp_arr = np.array(zp)
zp_arr

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [4]:
ks_arr = np.array(ks)
ks_arr

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [5]:
np.cov(zp_arr, ks_arr, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [6]:
cov = np.mean(ks_arr * zp_arr) - np.mean(ks_arr) * np.mean(zp_arr)
cov

9157.839999999997

In [7]:
ks_std = np.std(ks_arr, ddof=0)
ks_std

174.55340157098058

In [8]:
zp_std = np.std(zp_arr, ddof=0)
zp_std

59.115480206118605

In [9]:
cov_pirs = cov / (zp_std * ks_std)
cov_pirs

0.8874900920739158

In [10]:
np.corrcoef(zp_arr, ks_arr)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

2. Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [11]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
iq

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [12]:
X = np.mean(iq)
X

118.1

In [13]:
sigma = np.std(iq, ddof=1)
sigma

10.54566788359614

In [14]:
t_a2 = 2.262 # по таблице распределения Стьюдента при а = 0.025
n = 10


In [15]:
X1 = X + t_a2 * (sigma/sqrt(n))
X2 = X - t_a2 * (sigma/sqrt(n))

In [16]:
print([X2, X1])

[110.55660776308164, 125.64339223691834]


3. Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [17]:
X = 174.2
sigma = 5
n = 27
Z_a2 = 1.96

In [18]:
X1 = X + Z_a2 * sigma/sqrt(n)
X2 = X - Z_a2 * sigma/sqrt(n)

In [19]:
print([X2, X1])

[172.31398912064722, 176.08601087935276]
