### Урок 8. Домашняя работа

1. Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов. Даны значения роста в трех группах случайно выбранных спортсменов: Футболисты: 173, 175, 180, 178, 177, 185, 183, 182. Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180. Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170. alpha = 0.05.

In [1]:
import numpy as np
from scipy import stats

In [2]:
football_players = np.array([173, 175, 180, 178, 177, 185, 183, 182])
football_players

array([173, 175, 180, 178, 177, 185, 183, 182])

In [3]:
hockey_players = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
hockey_players

array([177, 179, 180, 188, 177, 172, 171, 184, 180])

In [11]:
weightlifters = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])
weightlifters

array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

Найдём Fнаблюд.

In [10]:
stats.f_oneway(football_players, hockey_players, weightlifters)

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)

Найдём Fкритич.

In [8]:
n = len(football_players) + len(hockey_players) + len(weightlifters)
n

28

In [9]:
stats.f.ppf(0.95, 2, n)

3.340385558237759

Вывод: Так как Fнаблюд > Fкрит мы попадаем в область гипотезы Н1 соответственно, есть статистически значимые различия среднего роста между cпортсменами